// State constants + transitions. PRD §6.
// v2 rate-mode states (RATE_*) are additive — build mode never enters them.
// See src/state/rate-router.js for the rate-mode state machine.
const STATES = Object.freeze({
  NEW: 'NEW',
  AWAITING_MODE_SELECT: 'AWAITING_MODE_SELECT',
  AWAITING_CONFIRM_START: 'AWAITING_CONFIRM_START',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_EMAIL: 'AWAITING_EMAIL',
  AWAITING_LINKEDIN: 'AWAITING_LINKEDIN',
  AWAITING_GITHUB: 'AWAITING_GITHUB',
  AWAITING_CODING_PROFILES: 'AWAITING_CODING_PROFILES',
  AWAITING_EDUCATION: 'AWAITING_EDUCATION',
  AWAITING_CGPA: 'AWAITING_CGPA',
  AWAITING_JD: 'AWAITING_JD',
  AWAITING_SKILLS: 'AWAITING_SKILLS',
  AWAITING_COURSEWORK: 'AWAITING_COURSEWORK',
  AWAITING_EXPERIENCE: 'AWAITING_EXPERIENCE',
  AWAITING_PROJECTS: 'AWAITING_PROJECTS',
  AWAITING_POR: 'AWAITING_POR',
  AWAITING_CERTS: 'AWAITING_CERTS',
  AWAITING_ACHIEVEMENTS: 'AWAITING_ACHIEVEMENTS',
  GENERATING: 'GENERATING',
  DELIVERED: 'DELIVERED',
  AWAITING_EDIT_OR_DONE: 'AWAITING_EDIT_OR_DONE',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PAID_COMPLETE: 'PAID_COMPLETE',

  // ─── v2 rate mode ──────────────────────────────────────────────
  // Entered only when session.mode === 'rate'. Build mode never enters these.
  RATE_AWAITING_PDF:      'RATE_AWAITING_PDF',
  RATE_ASKING_LINKS:      'RATE_ASKING_LINKS', // between PDF and role — proactively ask for missing critical URLs
  RATE_AWAITING_ROLE:     'RATE_AWAITING_ROLE',
  RATE_SCORING:           'RATE_SCORING',
  RATE_SHOWING_SCORE:     'RATE_SHOWING_SCORE',
  RATE_AWAITING_PAYMENT:  'RATE_AWAITING_PAYMENT',
  RATE_IMPROVING:         'RATE_IMPROVING',
  RATE_DELIVERED:         'RATE_DELIVERED',
});

// Rate-mode terminal + collection states. Convenience predicate for the main
// router / whatsapp.js so mode-aware checks (e.g. "allow PDF upload only in
// RATE_AWAITING_PDF") don't reach into rate-router internals.
const RATE_STATES = Object.freeze(new Set([
  'RATE_AWAITING_PDF',
  'RATE_ASKING_LINKS',
  'RATE_AWAITING_ROLE',
  'RATE_SCORING',
  'RATE_SHOWING_SCORE',
  'RATE_AWAITING_PAYMENT',
  'RATE_IMPROVING',
  'RATE_DELIVERED',
]));

// Linear Phase 2 transitions. Phases 4-7 are free-form (PRD §6).
const NEXT_STATE = Object.freeze({
  [STATES.NEW]: STATES.AWAITING_CONFIRM_START,
  [STATES.AWAITING_CONFIRM_START]: STATES.AWAITING_NAME,
  [STATES.AWAITING_NAME]: STATES.AWAITING_EMAIL,
  [STATES.AWAITING_EMAIL]: STATES.AWAITING_LINKEDIN,
  [STATES.AWAITING_LINKEDIN]: STATES.AWAITING_GITHUB,
  [STATES.AWAITING_GITHUB]: STATES.AWAITING_CODING_PROFILES,
  [STATES.AWAITING_CODING_PROFILES]: STATES.AWAITING_EDUCATION,
  [STATES.AWAITING_EDUCATION]: STATES.AWAITING_CGPA,
  [STATES.AWAITING_CGPA]: STATES.AWAITING_JD,
  [STATES.AWAITING_JD]: STATES.AWAITING_SKILLS,
  [STATES.AWAITING_SKILLS]: STATES.AWAITING_COURSEWORK,
  [STATES.AWAITING_COURSEWORK]: STATES.AWAITING_EXPERIENCE,
  [STATES.AWAITING_EXPERIENCE]: STATES.AWAITING_PROJECTS,
  [STATES.AWAITING_PROJECTS]: STATES.AWAITING_POR,
  [STATES.AWAITING_POR]: STATES.AWAITING_CERTS,
  [STATES.AWAITING_CERTS]: STATES.AWAITING_ACHIEVEMENTS,
  [STATES.AWAITING_ACHIEVEMENTS]: STATES.GENERATING,
});

// Sections where "skip" is valid (PRD §5 Phase 2 table — "Optional? Yes" rows).
// AWAITING_CGPA added 2026-06-25 per Meet's pilot feedback — many freshers
// either don't have a current CGPA, don't want to share it, or are between
// semesters; the bot should not block on it.
const OPTIONAL_STATES = new Set([
  STATES.AWAITING_LINKEDIN,
  STATES.AWAITING_GITHUB,
  STATES.AWAITING_CODING_PROFILES,
  STATES.AWAITING_CGPA,
  STATES.AWAITING_COURSEWORK,
  STATES.AWAITING_EXPERIENCE,
  STATES.AWAITING_PROJECTS,
  STATES.AWAITING_POR,
  STATES.AWAITING_CERTS,
  STATES.AWAITING_ACHIEVEMENTS,
]);

// Phase 2 collection states (all states asking the student a question that the LLM extracts from).
const PHASE_2_STATES = new Set([
  STATES.AWAITING_NAME,
  STATES.AWAITING_EMAIL,
  STATES.AWAITING_LINKEDIN,
  STATES.AWAITING_GITHUB,
  STATES.AWAITING_CODING_PROFILES,
  STATES.AWAITING_EDUCATION,
  STATES.AWAITING_CGPA,
  STATES.AWAITING_JD,
  STATES.AWAITING_SKILLS,
  STATES.AWAITING_COURSEWORK,
  STATES.AWAITING_EXPERIENCE,
  STATES.AWAITING_PROJECTS,
  STATES.AWAITING_POR,
  STATES.AWAITING_CERTS,
  STATES.AWAITING_ACHIEVEMENTS,
]);

module.exports = { STATES, NEXT_STATE, OPTIONAL_STATES, PHASE_2_STATES, RATE_STATES };
