// State constants + transitions. PRD §6.
const STATES = Object.freeze({
  NEW: 'NEW',
  AWAITING_CONFIRM_START: 'AWAITING_CONFIRM_START',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_EMAIL: 'AWAITING_EMAIL',
  AWAITING_LINKEDIN: 'AWAITING_LINKEDIN',
  AWAITING_GITHUB: 'AWAITING_GITHUB',
  AWAITING_CODING_PROFILES: 'AWAITING_CODING_PROFILES',
  AWAITING_EDUCATION: 'AWAITING_EDUCATION',
  AWAITING_CGPA: 'AWAITING_CGPA',
  AWAITING_JD: 'AWAITING_JD',
  AWAITING_SKILLS: 'AWAITING_SKILLS',
  AWAITING_COURSEWORK: 'AWAITING_COURSEWORK',
  AWAITING_EXPERIENCE: 'AWAITING_EXPERIENCE',
  AWAITING_PROJECTS: 'AWAITING_PROJECTS',
  AWAITING_POR: 'AWAITING_POR',
  AWAITING_CERTS: 'AWAITING_CERTS',
  AWAITING_ACHIEVEMENTS: 'AWAITING_ACHIEVEMENTS',
  GENERATING: 'GENERATING',
  DELIVERED: 'DELIVERED',
  AWAITING_EDIT_OR_DONE: 'AWAITING_EDIT_OR_DONE',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PAID_COMPLETE: 'PAID_COMPLETE',
});

// Linear Phase 2 transitions. Phases 4-7 are free-form (PRD §6).
const NEXT_STATE = Object.freeze({
  [STATES.NEW]: STATES.AWAITING_CONFIRM_START,
  [STATES.AWAITING_CONFIRM_START]: STATES.AWAITING_NAME,
  [STATES.AWAITING_NAME]: STATES.AWAITING_EMAIL,
  [STATES.AWAITING_EMAIL]: STATES.AWAITING_LINKEDIN,
  [STATES.AWAITING_LINKEDIN]: STATES.AWAITING_GITHUB,
  [STATES.AWAITING_GITHUB]: STATES.AWAITING_CODING_PROFILES,
  [STATES.AWAITING_CODING_PROFILES]: STATES.AWAITING_EDUCATION,
  [STATES.AWAITING_EDUCATION]: STATES.AWAITING_CGPA,
  [STATES.AWAITING_CGPA]: STATES.AWAITING_JD,
  [STATES.AWAITING_JD]: STATES.AWAITING_SKILLS,
  [STATES.AWAITING_SKILLS]: STATES.AWAITING_COURSEWORK,
  [STATES.AWAITING_COURSEWORK]: STATES.AWAITING_EXPERIENCE,
  [STATES.AWAITING_EXPERIENCE]: STATES.AWAITING_PROJECTS,
  [STATES.AWAITING_PROJECTS]: STATES.AWAITING_POR,
  [STATES.AWAITING_POR]: STATES.AWAITING_CERTS,
  [STATES.AWAITING_CERTS]: STATES.AWAITING_ACHIEVEMENTS,
  [STATES.AWAITING_ACHIEVEMENTS]: STATES.GENERATING,
});

// Sections where "skip" is valid (PRD §5 Phase 2 table — "Optional? Yes" rows).
const OPTIONAL_STATES = new Set([
  STATES.AWAITING_LINKEDIN,
  STATES.AWAITING_GITHUB,
  STATES.AWAITING_CODING_PROFILES,
  STATES.AWAITING_COURSEWORK,
  STATES.AWAITING_EXPERIENCE,
  STATES.AWAITING_PROJECTS,
  STATES.AWAITING_POR,
  STATES.AWAITING_CERTS,
  STATES.AWAITING_ACHIEVEMENTS,
]);

// Phase 2 collection states (all states asking the student a question that the LLM extracts from).
const PHASE_2_STATES = new Set([
  STATES.AWAITING_NAME,
  STATES.AWAITING_EMAIL,
  STATES.AWAITING_LINKEDIN,
  STATES.AWAITING_GITHUB,
  STATES.AWAITING_CODING_PROFILES,
  STATES.AWAITING_EDUCATION,
  STATES.AWAITING_CGPA,
  STATES.AWAITING_JD,
  STATES.AWAITING_SKILLS,
  STATES.AWAITING_COURSEWORK,
  STATES.AWAITING_EXPERIENCE,
  STATES.AWAITING_PROJECTS,
  STATES.AWAITING_POR,
  STATES.AWAITING_CERTS,
  STATES.AWAITING_ACHIEVEMENTS,
]);

module.exports = { STATES, NEXT_STATE, OPTIONAL_STATES, PHASE_2_STATES };
